In [39]:
import pandas as pd
import numpy as np

In [40]:
np.random.seed(42)
n_rows = 1000
data = {'color':np.random.choice(['red','blue','green'],n_rows),
        'size':np.random.choice(['small','medium','large'],n_rows),
        'material':np.random.choice(['plastic','metal','wood'],n_rows),
        'price':np.random.randint(10,500,n_rows)}

df = pd.DataFrame(data)

In [41]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [42]:
# from category_encoders import TargetEncoder

In [43]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder

In [44]:
X = df.drop(columns="price")
y=df.price

In [45]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42,train_size=0.8)

# Label Encoder

In [46]:
label_encoder = LabelEncoder()
# updated_xtrain = labe_encoder.fit_transform(xtrain) # we will get error

In [47]:
label_encoder.fit_transform(xtrain['color'])

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 2,
       0, 2, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 1,
       0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 2, 2,
       0, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2,
       1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       1, 0, 0, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2,
       0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 1,
       0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1,
       2, 1, 0, 2, 2, 0, 0, 1])

In [48]:
# label_encoder.transform(xtest)  #ValueError: y should be a 1d array, got an array of shape (200, 3) instead.

In [49]:
new_input =['red','red']
label_encoder.transform(new_input)

array([2, 2])

# OneHot encoder

In [50]:
onehot_encoder = OneHotEncoder()
values = onehot_encoder.fit_transform(xtrain)
values = values.toarray()
columns = onehot_encoder.get_feature_names_out()

In [51]:
pd.DataFrame(values,columns = columns)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
796,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
797,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
798,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
799,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [52]:
# values = onehot_encoder.fit_transform(xtrain[['color']])
# values = values.toarray()

In [53]:

onehot_encoder = OneHotEncoder(sparse_output=False)
values = onehot_encoder.fit_transform(xtrain)
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [54]:
# onehot_encoder.transform(xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.
# Feature names seen at fit time, yet now missing:
# - material

In [55]:
onehot_encoder.transform(xtest) #valid

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [56]:
# unknown values
# new_input = [['red','large'],['blue','small']] #ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
# onehot_encoder.transform(new_input)

In [57]:
new_input = [['red','large','plastic'],['blue','small','wood']]
onehot_encoder.transform(new_input)

c:\Users\Test\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [58]:
# new_input = [['red','large','rubber'],['blue','small','wood']] #ValueError: Found unknown categories ['rubber'] in column 2 during transform
# onehot_encoder.transform(new_input)

In [59]:
onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
updated_xtrain = onehot_encoder.fit_transform(xtrain)
new_input = [['red1','large','plastic'],['blue','small','wood']] 
onehot_encoder.transform(new_input)

c:\Users\Test\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [60]:
onehot_encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

# Ordinal Encoder

In [61]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
updated_xtrain = ordinal_encoder.fit_transform(xtrain)
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [62]:
ordinal_encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [63]:
# updated_xtrain = ordinal_encoder.fit_transform(xtrain['color'])  ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead

In [64]:
updated_xtest = ordinal_encoder.transform(xtest)
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 2., 0.],
       [2., 2., 2.],
       [0., 2., 2.],
       [0., 2., 0.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 2., 1.],
       [2., 1., 2.],
       [2., 2., 2.],
       [1., 2., 1.],
       [2., 1., 0.],
       [2., 2., 1.],
       [1., 1., 1.],
       [2., 0., 0.],
       [1., 0., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 0., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [0., 2., 2.],
       [2., 2., 0.],
       [0., 0., 2.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 0., 2.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 2., 1.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 2., 1.],
       [0., 0., 2.],
       [0., 0., 2.],
       [2., 0., 2.],
       [1., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 0., 0.],
       [2., 0., 0.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 2., 2.],
       [2., 2., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [0., 2., 2.],
       [2., 1., 1.],
       [1., 2., 1.],
       [2., 1., 2.],
       [0., 0., 1.],
       [2., 1., 2.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.],
       [2., 0., 2.],
       [2., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [0., 1., 2.],
       [2., 1., 2.],
       [2., 1., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 2., 0.],
       [2., 1., 1.],
       [2., 1., 2.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 1., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [0., 0., 2.],
       [0., 1., 0.],
       [2., 2., 2.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 2., 0.],
       [2., 2., 2.],
       [1., 2., 0.],
       [0., 0., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 1., 0.],
       [2., 1., 0.],
       [0., 1., 2.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [1., 2., 0.],
       [2., 0., 0.],
       [2., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [65]:
# updated_xtest = ordinal_encoder.transform(xtest['color']) #ValueError: Expected a 2-dimensional container but got <class 'pandas.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [66]:
#unknown values
# new_input = [['red1','large','plastic'],['blue','small','wood']]
# ordinal_encoder.transform(new_input)#ValueError: Found unknown categories ['red1'] in column 0 during transform

In [67]:
# handling unknown values
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain = ordinal_encoder.fit_transform(xtrain)
updated_xtest = ordinal_encoder.transform(xtest)
# new_data = [['red1','large','plastic'],['blue','small','wood']] # this will give warning because we have not passed the feature names
new_data = pd.DataFrame(data = [['red1','large','plastic'],['blue','small','wood']], columns=['color','size','material'] )  # this will not give warning
updated_new_data = ordinal_encoder.transform(new_data)
updated_new_data

array([[-1.,  0.,  1.],
       [ 0.,  2.,  2.]])

In [68]:
# With order
# ordinal_encoder = OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1) #ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
# ordinal_encoder.fit_transform(xtrain) # bcz xtrain is having three columns and categories have only 1 ctaegory ordeer so shape mismatch error 
# the orders in the ctegories and in the fit trasnform should match otherwise it will give value error

In [69]:
# ordinal_encoder = OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic','metal','wood']]) #ValueError: Found unknown categories ['red', 'green', 'blue'] in column 0 during fit
# ordinal_encoder.fit_transform(xtrain)

In [70]:
# ordinal_encoder = OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic','metal','wood']],handle_unknown='use_encoded_value') #TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.
# ordinal_encoder.fit_transform(xtrain)

In [71]:
ordinal_encoder = OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['plastic','wood','metal']],handle_unknown='use_encoded_value',unknown_value=-1)
ordinal_encoder.fit_transform(xtrain)
ordinal_encoder.transform(xtest)

array([[2., 0., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 0., 0.],
       [1., 1., 2.],
       [2., 2., 0.],
       [0., 2., 0.],
       [2., 0., 0.],
       [2., 2., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [2., 2., 0.],
       [1., 1., 1.],
       [0., 0., 2.],
       [2., 2., 2.],
       [0., 1., 1.],
       [2., 2., 0.],
       [2., 2., 1.],
       [1., 2., 2.],
       [0., 2., 2.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [0., 2., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 1., 0.],
       [2., 1., 2.],
       [2., 2., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [2., 0., 1.],
       [2., 1., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [2., 0., 1.],
       [2., 1., 1.],
       [0., 2., 2.],
       [2., 2., 0.],
       [1., 2., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [0., 0., 1.],
       [0., 1., 2.],
       [0., 2., 0.],
       [0., 2., 1.],
       [1., 2., 1.],
       [1., 0., 2.],
       [2., 0., 1.],
       [1., 0., 1.],
       [1., 0., 2.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 2., 2.],
       [2., 2., 0.],
       [1., 1., 1.],
       [1., 2., 2.],
       [0., 0., 0.],
       [2., 1., 1.],
       [2., 0., 1.],
       [0., 0., 0.],
       [2., 1., 2.],
       [2., 0., 0.],
       [0., 1., 0.],
       [2., 2., 2.],
       [0., 2., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [0., 1., 0.],
       [0., 1., 1.],
       [1., 2., 0.],
       [0., 2., 0.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [2., 2., 2.],
       [1., 0., 0.],
       [1., 0., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [1., 0., 1.],
       [2., 0., 2.],
       [1., 2., 1.],
       [2., 2., 1.],
       [2., 2., 0.],
       [1., 2., 2.],
       [2., 2., 1.],
       [1., 1., 2.],
       [0., 1., 2.],
       [2., 2., 1.],
       [1., 0., 0.],
       [1., 2., 2.],
       [0., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 0.],
       [1., 2., 2.],
       [2., 0., 1.],
       [0., 1., 0.],
       [2., 2., 0.],
       [2., 2., 2.],
       [2., 2., 1.],
       [2., 0., 0.],
       [1., 2., 1.],
       [1., 2., 1.],
       [2., 2., 1.],
       [0., 0., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [1., 2., 0.],
       [2., 0., 1.],
       [2., 1., 0.],
       [2., 1., 0.],
       [0., 2., 0.],
       [1., 2., 2.],
       [2., 0., 2.],
       [1., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 1.],
       [0., 2., 1.],
       [1., 0., 1.],
       [2., 0., 2.],
       [2., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [2., 1., 0.],
       [0., 0., 0.],
       [2., 1., 1.],
       [1., 2., 0.],
       [2., 1., 1.],
       [1., 2., 2.],
       [2., 1., 2.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 2.],
       [1., 2., 1.],
       [2., 2., 2.],
       [2., 2., 1.],
       [2., 2., 2.],
       [1., 2., 1.],
       [0., 2., 1.],
       [2., 0., 0.],
       [2., 0., 1.],
       [1., 2., 0.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 2., 1.],
       [1., 2., 2.],
       [1., 0., 2.],
       [2., 1., 0.],
       [2., 1., 1.],
       [0., 2., 0.],
       [0., 1., 2.],
       [0., 1., 0.],
       [2., 2., 0.],
       [1., 1., 0.],
       [2., 0., 2.],
       [0., 1., 2.],
       [2., 1., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 0.],
       [1., 2., 1.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 1., 2.],
       [1., 1., 2.],
       [2., 1., 0.],
       [1., 2., 0.],
       [2., 0., 2.],
       [2., 0., 1.],
       [0., 0., 2.],
       [1., 2., 2.],
       [0., 0., 0.],
       [0., 1., 2.],
       [1., 2., 2.],
       [1., 0., 2.],
       [1., 1., 2.],
       [2., 1., 2.],
       [1., 1., 1.],
       [1., 2., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 0., 2.],
       [0., 0., 0.],
       [0., 1., 0.]])

# Target encoders

In [72]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (2.4.2)
Requirement already satisfied: pandas>=1.0.5 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (3.0.1)
Requirement already satisfied: patsy>=0.5.1 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\test\appdata\roaming\python\python314\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\test\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\test\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\test\appdata\roaming\python\python314\site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Note: you may need to restart the kernel to use updated packages.

In [73]:
from category_encoders import TargetEncoder

In [ ]:
target_encoder = TargetEncoder(cols=['color'])  # we use cols parameter when we have mixed datatype columns
target_encoder.fit_transform(xtrain,ytrain) # it will not remove remaing colummns it only applies target encoder to only mentoioned column

          color    size material
29   253.164751   small     wood
535  256.408397  medium    metal
695  256.408397   small     wood
557  263.678700   small  plastic
836  253.164751   large  plastic
..          ...     ...      ...
106  263.678700   large  plastic
270  263.678700   small  plastic
860  256.408397   large  plastic
435  256.408397   small  plastic
102  253.164751   small  plastic

[800 rows x 3 columns]

In [76]:
target_encoder = TargetEncoder(cols=['color'],handle_unknown='value') 
target_encoder.fit_transform(xtrain,ytrain)

          color    size material
29   253.164751   small     wood
535  256.408397  medium    metal
695  256.408397   small     wood
557  263.678700   small  plastic
836  253.164751   large  plastic
..          ...     ...      ...
106  263.678700   large  plastic
270  263.678700   small  plastic
860  256.408397   large  plastic
435  256.408397   small  plastic
102  253.164751   small  plastic

[800 rows x 3 columns]

In [77]:
target_encoder.transform(xtest)

          color    size material
521  263.678700   small    metal
737  263.678700   small    metal
740  256.408397   small    metal
660  253.164751   small  plastic
411  256.408397  medium    metal
..          ...     ...      ...
408  253.164751   small    metal
332  263.678700   large    metal
208  263.678700   small    metal
613  253.164751   small  plastic
78   253.164751  medium  plastic

[200 rows x 3 columns]

In [79]:
# new_input = [['red','small','wood1']] #KeyError: 'color'
# target_encoder.transform(new_input)

In [81]:
new_input = pd.DataFrame({"color" : ['red1'], 'size' : ['small'], 'material': ['wood1'] })
target_encoder.transform(new_input)

      color   size material
0  257.8675  small    wood1

In [82]:
target_encoder = TargetEncoder(handle_unknown='value') 
target_encoder.fit_transform(xtrain,ytrain)

          color        size    material
29   253.164751  263.081784  245.481013
535  256.408397  254.923077  264.018248
695  256.408397  263.081784  245.481013
557  263.678700  263.081784  262.193772
836  253.164751  255.546512  262.193772
..          ...         ...         ...
106  263.678700  255.546512  262.193772
270  263.678700  263.081784  262.193772
860  256.408397  255.546512  262.193772
435  256.408397  263.081784  262.193772
102  253.164751  263.081784  262.193772

[800 rows x 3 columns]

In [84]:
# new_input = [['red','small','wood1']] 
# target_encoder.transform(new_input)
new_input = pd.DataFrame({"color" : ['red1'], 'size' : ['small'], 'material': ['wood1'] })
target_encoder.transform(new_input)

      color        size  material
0  257.8675  263.081784  257.8675